name: JobRecommender
channels:
  - defaults
dependencies:
  - ipykernel=6.31.0
  - matplotlib=3.10.6
  - numpy=2.2.5
  - pandas=2.3.3
  - polars=1.34.0
  - pip=25.2
  - python=3.10.19
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - tqdm=4.67.1
  - requests=2.32.5
  - pip:
      - --index-url https://download.pytorch.org/whl/cu118
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
